spring:
    datasource:
      dataSourceClassName: org.h2.jdbcx.JdbcDataSource
      url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      database: H2
      openInView: false
      show_sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop
        properties:
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: true
server:
      port: 8080
